# Generated by Django 5.0.6 on 2024-06-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(db_column='away', default='Reims', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='api.team', to_field='team', verbose_name='Equipo Visitante'),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalHome', models.IntegerField(verbose_name='Goles equipo local')),
                ('goalAway', models.IntegerField(verbose_name='Goles equipo visitante')),
                ('season', models.CharField(max_length=7, verbose_name='Temporada')),
                ('winner', models.CharField(max_length=59, verbose_name='Vencedor')),
                ('away', models.ForeignKey(db_column='away', default='Reims', on_delete=django.db.models.deletion.CASCADE, related_name='away_team_penaltis', to='api.team', to_field='team', verbose_name='Equipo Visitante')),
                ('home', models.ForeignKey(db_column='home', default='King of Europe', on_delete=django.db.models.deletion.CASCADE, related_name='home_team_penaltis', to='api.team', to_field='team', verbose_name='Equipo Local')),
                ('round', models.ForeignKey(db_column='round', default='final', on_delete=django.db.models.deletion.CASCADE, related_name='round_penaltis', to='api.round', to_field='round', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Tanda de penaltis',
                'verbose_name_plural': 'Tandas de penaltis',
            },
        ),
    ]
