version: '3.8'

services:
  db: 
    image: mysql:latest
    restart: always
    container_name: db-champions
    volumes:
      - .mysql-db:/var/lib/mysql
      - ./backend/mysqldata:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=championsleague
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - championsnet

  backend:
    image: pycampadb/tandemsoftware-backend:latest
    container_name: djchampions
    command: ["sh", "-c", "python wait_for_mysql.py && python manage.py makemigrations api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=championsleague
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=db
    networks:
      - championsnet
    depends_on:
      - db

  frontend:
    image: pycampadb/tandemsoftware-frontend:latest
    container_name: ionicucl
    ports:
      - "8100:8100"
    networks:
      - championsnet
    environment:
      - IONIC_APP_BACKEND_URL=http://tandemsoftware-backend:8000

networks:
  championsnet:
    driver: bridge

volumes:
  mysql-db: 